name: gleap_http_interceptor
description: A Http Interceptor for Gleap
version: 1.1.0
homepage: https://gleap.io

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http_interceptor: ^1.0.2
  gleap_sdk: '>=6.3.7'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
